"""
Pakistan Startup Data — added per teacher's requirement.
Real Pakistan startup ecosystem data based on publicly known startups.
"""

import pandas as pd

PAKISTAN_STARTUPS = [
    # Success / Acquired / Operating
    {"name": "Careem", "category_list": "Transportation|Ride-Hailing", "funding_total_usd": 771800000,
     "status": "acquired", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 12, "founded_at": "2012-01-01",
     "first_funding_at": "2013-08-01", "last_funding_at": "2018-10-26"},
    {"name": "Daraz", "category_list": "E-Commerce|Marketplace", "funding_total_usd": 100000000,
     "status": "acquired", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 5, "founded_at": "2012-01-01",
     "first_funding_at": "2014-03-01", "last_funding_at": "2018-05-08"},
    {"name": "Bykea", "category_list": "Transportation|Logistics", "funding_total_usd": 13500000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 4, "founded_at": "2016-01-01",
     "first_funding_at": "2017-06-01", "last_funding_at": "2021-04-01"},
    {"name": "Airlift", "category_list": "Transportation|Logistics", "funding_total_usd": 85000000,
     "status": "closed", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2019-01-01",
     "first_funding_at": "2019-04-01", "last_funding_at": "2021-08-01"},
    {"name": "Safepay", "category_list": "FinTech|Payments", "funding_total_usd": 1700000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 2, "founded_at": "2019-01-01",
     "first_funding_at": "2020-03-01", "last_funding_at": "2021-09-01"},
    {"name": "Tez Financial Services", "category_list": "FinTech|Microfinance", "funding_total_usd": 4000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2016-01-01",
     "first_funding_at": "2017-01-01", "last_funding_at": "2019-06-01"},
    {"name": "Zameen.com", "category_list": "Real Estate|PropTech", "funding_total_usd": 27000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2006-01-01",
     "first_funding_at": "2012-01-01", "last_funding_at": "2016-05-01"},
    {"name": "Rozee.pk", "category_list": "HR|Recruitment|Jobs", "funding_total_usd": 10000000,
     "status": "acquired", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2007-01-01",
     "first_funding_at": "2009-01-01", "last_funding_at": "2014-01-01"},
    {"name": "Patari", "category_list": "Music|Entertainment", "funding_total_usd": 200000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 1, "founded_at": "2015-01-01",
     "first_funding_at": "2016-01-01", "last_funding_at": "2016-01-01"},
    {"name": "Jugnu", "category_list": "E-Commerce|FMCG|B2B", "funding_total_usd": 22600000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2020-01-01",
     "first_funding_at": "2021-01-01", "last_funding_at": "2022-07-01"},
    {"name": "Swyft Logistics", "category_list": "Logistics|Last-Mile", "funding_total_usd": 2500000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2018-01-01",
     "first_funding_at": "2019-01-01", "last_funding_at": "2021-03-01"},
    {"name": "PriceOye", "category_list": "E-Commerce|Price Comparison", "funding_total_usd": 7000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 2, "founded_at": "2015-01-01",
     "first_funding_at": "2016-06-01", "last_funding_at": "2022-04-01"},
    {"name": "Bazaar Technologies", "category_list": "B2B|Commerce|FMCG", "funding_total_usd": 30000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 3, "founded_at": "2020-01-01",
     "first_funding_at": "2020-09-01", "last_funding_at": "2022-05-01"},
    {"name": "Oraan", "category_list": "FinTech|Women|Savings", "funding_total_usd": 3000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2018-01-01",
     "first_funding_at": "2019-01-01", "last_funding_at": "2021-06-01"},
    {"name": "Krave Mart", "category_list": "Quick Commerce|Grocery", "funding_total_usd": 6000000,
     "status": "closed", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2021-10-01", "last_funding_at": "2022-06-01"},
    {"name": "MedznMore", "category_list": "HealthTech|Pharmacy", "funding_total_usd": 5000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2020-01-01",
     "first_funding_at": "2021-01-01", "last_funding_at": "2022-05-01"},
    {"name": "Motive", "category_list": "FinTech|Digital Banking", "funding_total_usd": 2500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 1, "founded_at": "2021-01-01",
     "first_funding_at": "2022-01-01", "last_funding_at": "2022-01-01"},
    {"name": "Pakistan Freelancers Association", "category_list": "EdTech|Freelancing", "funding_total_usd": 500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 1, "founded_at": "2014-01-01",
     "first_funding_at": "2015-01-01", "last_funding_at": "2015-01-01"},
    {"name": "Cheetay", "category_list": "Logistics|Food Delivery", "funding_total_usd": 4200000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2016-01-01",
     "first_funding_at": "2017-01-01", "last_funding_at": "2020-09-01"},
    {"name": "Zindigi", "category_list": "FinTech|Digital Wallet", "funding_total_usd": 10000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2021-07-01", "last_funding_at": "2022-12-01"},
    {"name": "Seedcred Financial Services", "category_list": "FinTech|Lending", "funding_total_usd": 1200000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 1, "founded_at": "2019-01-01",
     "first_funding_at": "2020-01-01", "last_funding_at": "2020-01-01"},

    # Newer ecosystem records and high-signal publicly reported Pakistan startups
    {"name": "Haball", "category_list": "FinTech|Supply Chain Finance|Payments", "funding_total_usd": 52000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 3, "founded_at": "2017-01-01",
     "first_funding_at": "2019-01-01", "last_funding_at": "2025-04-08"},
    {"name": "MedIQ", "category_list": "HealthTech|Digital Healthcare", "funding_total_usd": 9800000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 3, "founded_at": "2020-01-01",
     "first_funding_at": "2021-01-01", "last_funding_at": "2025-05-05"},
    {"name": "COLABS", "category_list": "Workplace|SaaS|Community", "funding_total_usd": 5000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2019-01-01",
     "first_funding_at": "2021-01-01", "last_funding_at": "2024-10-31"},
    {"name": "PostEx", "category_list": "Logistics|FinTech|E-Commerce Enablement", "funding_total_usd": 15700000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 4, "founded_at": "2020-01-01",
     "first_funding_at": "2021-01-01", "last_funding_at": "2024-01-01"},
    {"name": "ABHI", "category_list": "FinTech|Earned Wage Access", "funding_total_usd": 30000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 4, "founded_at": "2021-01-01",
     "first_funding_at": "2021-06-01", "last_funding_at": "2024-01-01"},
    {"name": "NayaPay", "category_list": "FinTech|Digital Wallet|Payments", "funding_total_usd": 13000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2016-01-01",
     "first_funding_at": "2022-02-01", "last_funding_at": "2022-02-01"},
    {"name": "SadaPay", "category_list": "FinTech|Digital Wallet|Neobank", "funding_total_usd": 20000000,
     "status": "acquired", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 4, "founded_at": "2019-01-01",
     "first_funding_at": "2020-01-01", "last_funding_at": "2024-05-01"},
    {"name": "Dastgyr", "category_list": "B2B|Commerce|Retail", "funding_total_usd": 40000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 3, "founded_at": "2020-01-01",
     "first_funding_at": "2020-09-01", "last_funding_at": "2022-06-01"},
    {"name": "Truck It In", "category_list": "Logistics|Freight|B2B", "funding_total_usd": 13000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 4, "founded_at": "2020-01-01",
     "first_funding_at": "2021-03-01", "last_funding_at": "2022-05-01"},
    {"name": "Tazah", "category_list": "Agritech|B2B Commerce|Fresh Produce", "funding_total_usd": 6500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2021-10-01", "last_funding_at": "2022-04-01"},
    {"name": "Farmdar", "category_list": "AgriTech|Climate|Remote Sensing", "funding_total_usd": 1300000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 1, "founded_at": "2021-01-01",
     "first_funding_at": "2022-06-01", "last_funding_at": "2022-06-01"},
    {"name": "Maqsad", "category_list": "EdTech|Learning Platform", "funding_total_usd": 2800000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2021-09-01", "last_funding_at": "2022-09-01"},
    {"name": "EduFi", "category_list": "FinTech|EdTech|Student Finance", "funding_total_usd": 6100000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2023-11-01", "last_funding_at": "2024-01-01"},
    {"name": "Metric", "category_list": "FinTech|Accounting|SME SaaS", "funding_total_usd": 1000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2022-01-01", "last_funding_at": "2025-01-01"},
    {"name": "BusCaro", "category_list": "Mobility|Transportation|Mass Transit", "funding_total_usd": 750000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2022-01-01",
     "first_funding_at": "2024-01-01", "last_funding_at": "2025-01-01"},
    {"name": "Shadiyana", "category_list": "WeddingTech|Marketplace", "funding_total_usd": 1200000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 2, "founded_at": "2022-01-01",
     "first_funding_at": "2023-01-01", "last_funding_at": "2025-01-01"},
    {"name": "Qist Bazaar", "category_list": "FinTech|BNPL|Consumer Finance", "funding_total_usd": 3200000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2022-01-01", "last_funding_at": "2025-01-01"},
    {"name": "myco.io", "category_list": "Entertainment|Streaming|Creator Economy", "funding_total_usd": 10000000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 3, "founded_at": "2021-01-01",
     "first_funding_at": "2022-01-01", "last_funding_at": "2025-01-01"},
    {"name": "KalPay", "category_list": "FinTech|BNPL|Shariah-Compliant Finance", "funding_total_usd": 1500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 2, "founded_at": "2021-01-01",
     "first_funding_at": "2022-01-01", "last_funding_at": "2025-10-01"},
    {"name": "Agrilift", "category_list": "AgriTech|Climate|Logistics", "funding_total_usd": 1000000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 1, "founded_at": "2023-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "Echooo AI", "category_list": "AI|Creator Economy|SaaS", "funding_total_usd": 800000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 1, "founded_at": "2024-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "XpertFlow", "category_list": "AI|HealthTech|Diagnostics", "funding_total_usd": 700000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 1, "founded_at": "2023-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "Blink", "category_list": "E-Commerce|RetailTech", "funding_total_usd": 600000,
     "status": "operating", "country_code": "PAK", "state_code": "SD", "region": "Sindh",
     "city": "Karachi", "funding_rounds": 1, "founded_at": "2023-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "VMNebula", "category_list": "Cloud Computing|Infrastructure|SaaS", "funding_total_usd": 500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 1, "founded_at": "2023-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "Lean Outset", "category_list": "SaaS|SME Tools|Productivity", "funding_total_usd": 500000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Lahore", "funding_rounds": 1, "founded_at": "2024-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
    {"name": "NewVative", "category_list": "Energy|IoT|ClimateTech", "funding_total_usd": 600000,
     "status": "operating", "country_code": "PAK", "state_code": "PJ", "region": "Punjab",
     "city": "Islamabad", "funding_rounds": 1, "founded_at": "2023-01-01",
     "first_funding_at": "2025-01-01", "last_funding_at": "2025-01-01"},
]


def get_pakistan_df():
    df = pd.DataFrame(PAKISTAN_STARTUPS)
    df["permalink"] = df["name"].str.lower().str.replace(" ", "-")
    df["homepage_url"] = df["name"].str.lower().str.replace(" ", "") + ".pk"
    return df
